const UPDATE_FORCE_COMPLETE_UPDATE = 0x102;
const UPDATE_KEEP_MODEL = 0x101;
const UPDATE_DEFAULT = 0x100;

export default {
	UPDATE_FORCE_COMPLETE_UPDATE: UPDATE_FORCE_COMPLETE_UPDATE,
	UPDATE_KEEP_MODEL: UPDATE_KEEP_MODEL,
	UPDATE_DEFAULT: UPDATE_DEFAULT
};
